#ifndef TMEDIA_UNIT_CONVERSION_H
#define TMEDIA_UNIT_CONVERSION_H

#define GIGABYTES_TO_BYTES 1E9
#define BYTES_TO_GIGABYTES 1E-9

#define SECONDS_TO_NANOSECONDS 1E9
#define NANOSECONDS_TO_SECONDS 1E-9

#define SECONDS_TO_MILLISECONDS 1E3
#define MILLISECONDS_TO_SECONDS (1.0 / (SECONDS_TO_MILLISECONDS))

#define MILLISECONDS_TO_NANOSECONDS 1E6
#define NANOSECONDS_TO_MILLISECONDS 1E-6

#define MINUTES_TO_SECONDS 60
#define SECONDS_TO_MINUTES (1.0 / (MINUTES_TO_SECONDS))

#define HOURS_TO_SECONDS 3600
#define SECONDS_TO_HOURS (1.0 / (HOURS_TO_SECONDS))

#define DAYS_TO_SECONDS 86400
#define SECONDS_TO_DAYS (1.0 / (DAYS_TO_SECONDS))

#endif
