#ifndef ASCII_VIDEO_AVGUARD
#define ASCII_VIDEO_AVGUARD

extern "C" {
    #include <libavutil/version.h>
    #include <libavformat/version.h>
}

/** AVFrame.duration introduced in libavutil version 57.30.100 */
#define HAS_AVFRAME_DURATION (LIBAVUTIL_VERSION_MAJOR > 57 || (LIBAVUTIL_VERSION_MAJOR == 57 && LIBAVUTIL_VERSION_MINOR > 30) || (LIBAVUTIL_VERSION_MAJOR == 57 && LIBAVUTIL_VERSION_MINOR == 30 && LIBAVUTIL_VERSION_MICRO >= 100))
#define HAS_AVCHANNEL_LAYOUT (LIBAVUTIL_VERSION_MAJOR > 57 || (LIBAVUTIL_VERSION_MAJOR == 57 && LIBAVUTIL_VERSION_MINOR > 24) || (LIBAVUTIL_VERSION_MAJOR == 57 && LIBAVUTIL_VERSION_MINOR == 24 && LIBAVUTIL_VERSION_MICRO >= 100))
#define AV_FIND_BEST_STREAM_CONST_DECODER (LIBAVFORMAT_VERSION_MAJOR > 59 || (LIBAVFORMAT_VERSION_MAJOR == 59 && LIBAVFORMAT_VERSION_MINOR > 0) || (LIBAVFORMAT_VERSION_MAJOR == 59 && LIBAVFORMAT_VERSION_MINOR == 0 && LIBAVFORMAT_VERSION_MICRO >= 100))

#endif