#ifndef ASCII_VIDEO_MACROS
#define ASCII_VIDEO_MACROS

#define GIGABYTES_TO_BYTES 1000000000
#define BYTES_TO_GIGABYTES 1.0 / GIGABYTES_TO_BYTES

#define SECONDS_TO_NANOSECONDS 1000000000
#define NANOSECONDS_TO_SECONDS 1.0 / SECONDS_TO_NANOSECONDS
#define SECONDS_TO_MILLISECONDS 1000
#define MILLISECONDS_TO_SECONDS 1.0 / SECONDS_TO_MILLISECONDS

#define MILLISECONDS_TO_NANOSECONDS SECONDS_TO_NANOSECONDS / SECONDS_TO_MILLISECONDS

#define PACKET_RESERVE_SIZE 100000
#define VOLUME_CHANGE_AMOUNT 0.05
#define TIME_CHANGE_AMOUNT 10
#define TIME_CHANGE_WAIT_MILLISECONDS 25
#define PLAYBACK_SPEED_CHANGE_WAIT_MILLISECONDS 250
#define PLAYBACK_SPEED_CHANGE_INTERVAL 0.25

/* #define MAX_ASCII_IMAGE_WIDTH (long)16 * 16 */
/* #define MAX_ASCII_IMAGE_HEIGHT (long)9 * 16 */
/* #define FRAME_DATA_SIZE MAX_ASCII_IMAGE_WIDTH * MAX_ASCII_IMAGE_HEIGHT */
#endif
