#ifndef ASCII_VIDEO_UNIT_CONVERSION
#define ASCII_VIDEO_UNIT_CONVERSION

#define GIGABYTES_TO_BYTES 1000000000
#define BYTES_TO_GIGABYTES 1.0 / GIGABYTES_TO_BYTES

#define SECONDS_TO_NANOSECONDS 1000000000
#define NANOSECONDS_TO_SECONDS 1.0 / SECONDS_TO_NANOSECONDS
#define SECONDS_TO_MILLISECONDS 1000
#define MILLISECONDS_TO_SECONDS 1.0 / SECONDS_TO_MILLISECONDS

#define MILLISECONDS_TO_NANOSECONDS 1000000



/* #define MAX_ASCII_IMAGE_WIDTH (long)16 * 16 */
/* #define MAX_ASCII_IMAGE_HEIGHT (long)9 * 16 */
/* #define FRAME_DATA_SIZE MAX_ASCII_IMAGE_WIDTH * MAX_ASCII_IMAGE_HEIGHT */
#endif
